version: "3.9"

services:
  app:
    build:
      context: ./docker/php
    container_name: php_app
    volumes:
      - ./app:/var/www/app
      - ./public:/var/www/public
    networks:
      - app_net

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app_net

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_net

volumes:
  db_data:

networks:
  app_net:
